### ISSUE TITLE
 Manage Delivery is not working

### ISSUE THREAD

**Issue by Prontonation** [aws-samples/amazon-location-service-geotrack-vuejs#1]
Manage Delivery is not working 
error [object object] while adding new information

**Comment by arturlr** [comment]
There is known bug that requires you to calculate the route before saving a delivery. Would you mind checking if that solves your issues? I am working on a new release that will fix it.

**Comment by Prontonation** [comment]
yes it is also giving error also after doing the calculate the route. thank you for your  kind word and respond. your are great.

**Comment by Prontonation** [comment]
did u get time to check the issue?

**Comment by arturlr** [comment]
It should be fixed  now

**Comment by Prontonation** [comment]
in the home i do not see any device showing  tracking.geo.us-east-1.amazonaws.com/tracking/v0/trackers/geotrack-devx-tracker/get-positions
[HTTP/2 200 OK 324ms]

	
Errors	[]
DevicePositions	[]

**Comment by arturlr** [comment]
Updated the solution and fix this issue.
